# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

synth_idx_list_to_matrix <- function(synthetic_idx_ptr) {
    .Call(`_sceptre_synth_idx_list_to_matrix`, synthetic_idx_ptr)
}

synth_idx_list_to_r_list <- function(synthetic_idx_ptr) {
    .Call(`_sceptre_synth_idx_list_to_r_list`, synthetic_idx_ptr)
}

print_synth_idx_list_row <- function(synthetic_idx_ptr, idx) {
    invisible(.Call(`_sceptre_print_synth_idx_list_row`, synthetic_idx_ptr, idx))
}

estimate_theta <- function(y, mu, dfr, limit, eps) {
    .Call(`_sceptre_estimate_theta`, y, mu, dfr, limit, eps)
}

#' @title Fisher-Yates sampler
#' @description This function draws a without replacement sample using the Fisher-Yates sampling algorithm
#' @param n_tot the total number of cells
#' @param M the maximum number of cells in a given gRNA group
#' @param B the number of WOR samples to generate
#' @noRd
fisher_yates_samlper <- function(n_tot, M, B) {
    .Call(`_sceptre_fisher_yates_samlper`, n_tot, M, B)
}

#' @title Hybrid Fisher-Yates/IWOR sampler
#' @description This function draws an inductive without replacement sample using the hybrid Fisher-Yates/IWOR sampling algorithm (developed by Barry et al, to be described in a forthcoming preprint)
#' @param N the number of control cells
#' @param m the minumum number of cells in a given gRNA group
#' @param M the maximum number of cells in a given gRNA group
#' @param B the number of WOR samples to generate
#' @noRd
hybrid_fisher_iwor_sampler <- function(N, m, M, B) {
    .Call(`_sceptre_hybrid_fisher_iwor_sampler`, N, m, M, B)
}

crt_index_sampler <- function(fitted_probabilities, B) {
    .Call(`_sceptre_crt_index_sampler`, fitted_probabilities, B)
}

crt_index_sampler_fast <- function(fitted_probabilities, B) {
    .Call(`_sceptre_crt_index_sampler_fast`, fitted_probabilities, B)
}

run_low_level_test_full_v4 <- function(y, mu, a, w, D, trt_idxs, n_trt, use_all_cells, synthetic_idxs, B1, B2, B3, fit_skew_normal, return_resampling_dist) {
    .Call(`_sceptre_run_low_level_test_full_v4`, y, mu, a, w, D, trt_idxs, n_trt, use_all_cells, synthetic_idxs, B1, B2, B3, fit_skew_normal, return_resampling_dist)
}

sample_combinations <- function(undercover_group_size, n_pairs_to_sample, N_NONZERO_TRT, N_NONZERO_CNTRL, n_possible_groups, n_nonzero_m, n_nonzero_tot) {
    .Call(`_sceptre_sample_combinations`, undercover_group_size, n_pairs_to_sample, N_NONZERO_TRT, N_NONZERO_CNTRL, n_possible_groups, n_nonzero_m, n_nonzero_tot)
}

iterate_over_combinations <- function(n_nt_grnas, undercover_group_size, n_possible_groups) {
    .Call(`_sceptre_iterate_over_combinations`, n_nt_grnas, undercover_group_size, n_possible_groups)
}

sample_undercover_pairs <- function(n_nonzero_m, n_nonzero_tot, possible_groups_m, n_pairs_to_sample, N_NONZERO_TRT, N_NONZERO_CNTRL, low_moi, j, p, n_cells, n_genes, indiv_nt_grna_idxs) {
    .Call(`_sceptre_sample_undercover_pairs`, n_nonzero_m, n_nonzero_tot, possible_groups_m, n_pairs_to_sample, N_NONZERO_TRT, N_NONZERO_CNTRL, low_moi, j, p, n_cells, n_genes, indiv_nt_grna_idxs)
}

increment_matrix <- function(m) {
    invisible(.Call(`_sceptre_increment_matrix`, m))
}

compute_nt_nonzero_matrix_and_n_ok_pairs_v2 <- function(j, p, n_cells, grna_group_idxs, indiv_nt_grna_idxs, all_nt_idxs, to_analyze_response_idxs, to_analyze_grna_idxs, n_nonzero_trt_thresh, n_nonzero_cntrl_thresh, compute_n_ok_pairs, control_group_complement) {
    .Call(`_sceptre_compute_nt_nonzero_matrix_and_n_ok_pairs_v2`, j, p, n_cells, grna_group_idxs, indiv_nt_grna_idxs, all_nt_idxs, to_analyze_response_idxs, to_analyze_grna_idxs, n_nonzero_trt_thresh, n_nonzero_cntrl_thresh, compute_n_ok_pairs, control_group_complement)
}

compute_n_nonzero_trt_vector <- function(expression_vector, grna_group_idxs, grna_group_posits) {
    .Call(`_sceptre_compute_n_nonzero_trt_vector`, expression_vector, grna_group_idxs, grna_group_posits)
}

test_boost_sampler <- function(n) {
    .Call(`_sceptre_test_boost_sampler`, n)
}

test_std_sampler <- function(n) {
    .Call(`_sceptre_test_std_sampler`, n)
}

compute_empirical_p_value <- function(null_statistics, z_orig, side) {
    .Call(`_sceptre_compute_empirical_p_value`, null_statistics, z_orig, side)
}

fit_skew_normal_funct <- function(y) {
    .Call(`_sceptre_fit_skew_normal_funct`, y)
}

check_sn_tail <- function(y, xi_hat, omega_hat, alpha_hat) {
    .Call(`_sceptre_check_sn_tail`, y, xi_hat, omega_hat, alpha_hat)
}

fit_and_evaluate_skew_normal <- function(z_orig, null_statistics) {
    .Call(`_sceptre_fit_and_evaluate_skew_normal`, z_orig, null_statistics)
}

load_csr_row <- function(j, p, x, row_idx, n_cells) {
    .Call(`_sceptre_load_csr_row`, j, p, x, row_idx, n_cells)
}

obtain_pointer_vector <- function(i, dim) {
    .Call(`_sceptre_obtain_pointer_vector`, i, dim)
}

compute_cell_covariates_cpp <- function(i, p, x, n_genes, n_cells, mt_gene_idxs, compute_p_mito) {
    .Call(`_sceptre_compute_cell_covariates_cpp`, i, p, x, n_genes, n_cells, mt_gene_idxs, compute_p_mito)
}

compute_colwise_max <- function(i, p, x, n_cells) {
    .Call(`_sceptre_compute_colwise_max`, i, p, x, n_cells)
}

group_and_threshold <- function(j, p, x, row_idxs, threshold) {
    .Call(`_sceptre_group_and_threshold`, j, p, x, row_idxs, threshold)
}

