name: R-CMD-check

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - name: Install dependencies
      run: |
        install.packages(c("remotes", "covr"))
        remotes::install_deps(dependencies = TRUE)
    - name: Run test coverage
      run: covr::codecov()

