name: R-CMD-check

on:
  push:
    branches:
      # - main
      # - dev
      - code-cov
  pull_request:
    branches:
      # - main
      # - dev
      - code-cov

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.3'

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev

    - name: Install R dependencies
      env:
        GITHUB_PAT: ${{ secrets.CI_PAT }}
      run: |
        Rscript -e "Sys.setenv(CI_PAT = Sys.getenv('CI_PAT'))"
        Rscript -e "options(warn = 2)"
        Rscript -e "install.packages(c('remotes', 'covr'))"
        Rscript -e "remotes::install_github('Katsevich-Lab/sceptredata')"
        Rscript -e "remotes::install_deps(dependencies=TRUE)"

    - name: Generate coverage report
      run: Rscript -e "covr::coveralls(file='coverage.xml')" 
    - name: List files in the current directory
      run: ls -la


    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml



