name: R-CMD-check

on:
  push:
    branches:
      # - main
      # - dev
      - code-cov
  pull_request:
    branches:
      # - main
      # - dev
      - code-cov

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - name: Install dependencies
      run: |
        Rscript -e "install.packages(c('remotes', 'covr'))"
        Rscript -e "remotes::install_deps(dependencies = TRUE)"
    - name: Generate coverage report
      run: Rscript -e "covr::codecov(quiet = FALSE)" 
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1

